version: '3'

services:
    web:
        build: .
        volumes:
            - ./www:/www

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
        depends_on:
            - web
        ports:
            - 8083:8082
